
GET http://localhost:8080/user

> {%
 client.test("Request executed succesfully", function() {
   client.assert(response.status == 200, "Response status is not 200")
 });
 %}

###

GET http://localhost:8080/ingredients

> {%
 client.test("Request executed succesfully", function() {
   client.assert(response.status == 200, "Response status is not 200")
 });
 %}

###

GET http://localhost:8080/recipes

> {%
 client.test("Request executed succesfully", function() {
   client.assert(response.status == 200, "Response status is not 200")
 });
 %}

###

POST http://localhost:8080/ingredients
Content-Type: application/x-www-form-urlencoded

name=Patlidzan&veggie=true

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}

###

DELETE http://localhost:8080/ingredients/Kashkaval

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
