
GET http://localhost:8080/user

> {%
 client.test("Request executed succesfully", function() {
   client.assert(response.status == 200, "Response status is not 200")
 });
 %}

###

GET http://localhost:8080/ingredients

> {%
 client.test("Request executed succesfully", function() {
   client.assert(response.status == 200, "Response status is not 200")
 });
 %}

###

GET http://localhost:8080/recipes

> {%
 client.test("Request executed succesfully", function() {
   client.assert(response.status == 200, "Response status is not 200")
 });
 %}

###

POST http://localhost:8080/ingredients
Content-Type: application/x-www-form-urlencoded

name=Patlidzan&veggie=true

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}

###

DELETE http://localhost:8080/ingredients/Kashkaval

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

POST http://localhost:8080/recipes
Content-Type: application/x-www-form-urlencoded

name=tava&description=opis&img=url na slika&veggie=false&ingredients=Kashkaval,Kecap,Sunka

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}

###

GET http://localhost:8080/recipes?name=tava

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###


POST http://localhost:8080/user
Content-Type: application/x-www-form-urlencoded

username=Sfaf&email=jovan@gmail.com&password=laptop&bio=jas sum mnogu dobar decko

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}

###